export { default as createAnswers } from './answer.createAnswers.service'
export { default as createAnswer } from './answer.createAnswer.service'
export { default as getAnswers } from './answer.getAnswers.service'
export { default as updateAnswer } from './answer.updateAnswer.service'
export { default as deleteAnswer } from './answer.deleteAnswer.service'
export { default as deleteAnswers } from './answer.deleteAnswers.service'
export { default as getCorrectAnswerOfQuizQuestion } from './answer.getCorrectAnswerOfQuizQuestion.service'
